config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  resources :houses do
    member do
      post :toggle_favourites
    end
    resources :offers, only: %i[index create update] do
      member do
        post :accept
        post :decline
      end
    end
    collection do
      get 'my_listings'
      get 'my_offers'
    end
  end
  resources :offers, only: [:destroy]
  resources :favourites, only: :index
end

app/controllers/houses_controller.rb
class HousesController < ApplicationController
  before_action :set_house, only: %i[show edit update destroy toggle_favourites]
  skip_before_action :authenticate_user!, only: %i[show index]

  # GET / houses

  def index
    @houses = policy_scope(House)

    if params[:query].present?
      @houses = @houses.search_by_address(params[:query])
    end

    if params[:min_price].present?
      @houses = @houses.where("price >= ?", params[:min_price])
    end

    if params[:max_price].present?
      @houses = @houses.where("price <= ?", params[:max_price])
    end

    if params[:prop_type].present?
      @houses = @houses.where(property_type: params[:prop_type])
    end

    # if params[:bedrm].present?
    #   @houses = @houses.where(bedroom: params[:bedrm])
    # end

    if params[:region].present?
      @houses = @houses.where("region ILIKE ?", "%#{params[:region]}%")
    end

    selected_bedrooms = []
    selected_bedrooms << 1 if params[:bedrooms_1] == "1"
    selected_bedrooms << 2 if params[:bedrooms_2] == "1"
    selected_bedrooms << 3 if params[:bedrooms_3] == "1"
    selected_bedrooms << 4 if params[:bedrooms_4] == "1"
    selected_bedrooms << 5 if params[:bedrooms_5] == "1"

    if selected_bedrooms.present?
      @houses = @houses.where(bedroom: selected_bedrooms)
    end
    # The `geocoded` scope filters only flats with coordinates
    @markers = @houses.geocoded.map do |house|
      {
        lat: house.latitude,
        lng: house.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: { house: house })
      }
    end
  end

  # GET / houses/:id
  def show
    @markers = [
      {
        lat: @house.latitude,
        lng: @house.longitude
      }]
    @offer = Offer.new
  end

  # GET / houses/new
  def new
    @house = House.new
    authorize(@house)
  end

  def edit
  end

  def create
    @house = House.new(house_params)
    @house.user = current_user
    authorize(@house)

    if @house.save
      redirect_to house_path(@house)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @house.update(house_params)
    if @house.save
      redirect_to @house
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @house.destroy
    redirect_to houses_path, status: :see_other
  end

  # def category
  #   @category = params[:category]
  #   @houses = House.where(category: @category[0...-1])
  # end

  def toggle_favourites
    if current_user.favourites.exists?(house_id: @house.id)
      current_user.favourites.where(house_id: @house.id).destroy_all
      # flash[:notice] = "Page removed from favourites"
    else
      Favourite.create(user: current_user, house_id: @house.id)
      # flash[:notice] = "Page added to favourites"
    end
  end

  def my_listings
    @user_houses = current_user.houses
  end

  def my_offers
    @user_offers = current_user.offers.includes(:house)
  end

  private

  def set_house
    @house = House.find(params[:id])
    authorize(@house)
  end

  def house_params
    params.require(:house).permit(:address, :price, :bedroom, :bathroom, :square_feet, :description, :property_type, :tenure, :region, photos: [])
  end
end

app/views/houses/_current_offers.html.erb
<table class="table table-striped table-hover" >
  <thead>
  <tr>
    <th>#</th>
    <th>Price</th>
    <th>Bidder</th>
    <th>Status</th>
    <th>Date Created</th>
  </tr>
  </thead>
  <tbody>
  <% house.offers.order(price: :desc).each_with_index do |offer, index| %>
    <tr data-controller="accept-offers">
      <td><%= index + 1 %></td>
      <td><%= number_to_currency(offer.price, precision: 0) %></td>
      <td><%= offer.user.first_name  %></td>
      <td data-accept-offers-target="status" ><%= offer.status  %></td>
      <td><%= offer.created_at.strftime('%Y-%m-%d') %></td>
      <% if offer.user == current_user && offer.status == 'Pending'  %>
        <td>
          <div class="d-flex flex-column">
            <button type="button" class="btn btn-secondary btn-sm w-100 mb-1" data-bs-toggle="modal" data-bs-target="#offer-<%= offer.id%>">
              Edit
            </button>
            <%= link_to 'Delete', offer_path(offer), class: "btn btn-warning btn-sm", data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
          </div>
        </td>
      <% else %>
        <td></td>
      <% end %>
      <% if House.find(offer.house_id).user == current_user && offer.status == 'Pending'  %>
        <td>
          <div>
            <%= button_to 'Accept', accept_house_offer_path(offer.house, offer), method: :post, class: 'update-offer-button btn btn-success btn-sm w-100 mb-1', data: { accept_offers_target: "accept", action: "click->accept-offers#accept" } %>
            <%= button_to 'Decline', decline_house_offer_path(offer.house, offer), method: :post, class: 'decline-offer-button btn btn-danger btn-sm w-100', data: { accept_offers_target: "decline", action: "click->accept-offers#decline" } %>
          </div>
        </td>
      <% else %>
        <td></td>
      <% end %>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/houses/_form.html.erb
<%= simple_form_for(@house) do |f| %>
    <%= f.input :photos, as: :file, input_html: { multiple: true } %>
    <%= f.input :address,
        # address autocomplete
        input_html: {data: {address_autocomplete_target: "address"}, class: "d-none"},
        wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}}
    %>
    <!-- Hidden input for region which gets autofilled -->
    <%= f.input :region, input_html: { value: @extracted_region_name, readonly: true, class: 'greyed-out' } %>
    <%= f.input :price, as: :text, placeholder: "Price" %>
    <%= f.input :bedroom, placeholder: "bedroom" , collection: House::BEDROOM %>
    <%= f.input :bathroom, placeholder: "bathroom" , collection: House::BATHROOM %>
    <%= f.input :square_feet, as: :text, placeholder: "square feet?" %>
    <%= f.input :description, placeholder: "describe this place" %>
    <%= f.input :property_type, placeholder: "property type", collection: House::PROPERTY_TYPE %>
    <%= f.input :tenure, placeholder: "how many years tenure", collection: House::TENURE_CAT  %>
    <%= f.button :submit, class: "btn btn-success" %>
  <% end %>

app/views/houses/_info_window.html.erb
<div data-controller="scroll" data-scroll-house-value="<%= house.id %>">
  <h4><%= house.address %></h4>
  <p> Minimum Ask Price: $<%= house.price %> </p>
  <p> Type: <%= house.property_type %> </p>
</div>

app/views/houses/_listing.html.erb
<div class="row">
  <% @houses.each do |house| %>
    <div class="col-md-6 mb-3" id="house-<%= house.id %>" class="scroll-offset">
      <div class="card" style="width: 100%;">
        <!-- Can replace the following image tag with your actual image using image_tag -->
        <% if house.photos.attached? %>
          <%= image_tag(cl_image_path house.photos.first.key, width: 400, height: 300, crop: :fill) %>
        <% end %>
        <div class="card-body">
          <h5 class="card-title"><%= house.address %></h5>
          <p class="card-text">Region: <%= house.region %></p>
          <p class="card-text"><strong>Minimum Ask Price:</strong> <%= number_to_currency(house.price, precision: 0) %></p>
          <p class="card-text">Highest Offered Price: <%= number_to_currency(house.offers.maximum(:price), precision: 0) %></p>
          <div class="d-flex justify-content-between mt-4">
            <div class="d-flex flex-column align-items-start">
              <p class="card-text">Size in sqft: <br><%= house.square_feet %>sqft</p>
              <p class="card-text">Bedrooms: <%= house.bedroom %></p>
            </div>
            <div class="d-flex flex-column align-items-end">
              <p class="card-text text-end">Price per sqft: <br><%= number_to_currency((house.price.to_f / house.square_feet).round(2)) %>psf</p>
              <p class="card-text">Bathrooms: <%= house.bathroom %></p>
            </div>
          </div>
          <div class="d-flex justify-content-between mt-4">
            <%= link_to "Check this out!", house_path(house), class: "btn btn-primary" %>
            <p class="card-text">Listed By: <%= house.user[:first_name] %></p>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/houses/edit.html.erb
<h1>Edit <%= @house.address %></h1>
<%= render 'form', house: @house %>

app/views/houses/index.html.erb
<div class="container">
  <h1>All Houses</h1>

  <div class="mb-3">
    <%= render 'pages/search' %>
  </div>


<div class="container">
  <hr>
  <%= link_to 'Looking to sell? Create new listing', new_house_path, class: "btn btn-success"%>
  <hr>
  <div class="row">
    <div class="col-md-8">
      <div class="row">
        <%= render 'listing' %>
      </div>
    </div>
    <div class="col-md-4">
      <%# Geocoding for all houses in the database %>
      <div data-controller="map"
          id='map'
          data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"
          data-map-markers-value="<%= @markers.to_json %>"
          style="height: 100vh; position: sticky; top: 0;">
      </div>
    </div>
  </div>
</div>
</div>

app/views/houses/my_listings.html.erb
<div class="container mt-5">
  <div>
    <%= link_to :back, class: "btn" do %>
        <i class="fas fa-arrow-left"></i>
      <% end %>
  </div>
<div class="container mt-5">
  <div class="row">
    <div class="col-md-6 offset-md-3 text-center">
      <h1>My Listings</h1>
    </div>
    <div class="col-md-3 text-right mb-3">
      <% if @user_houses.present? %>
        <%= link_to "Create a new listing", new_house_path, class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>

  <div class="row justify-content-center mt-5">
    <% if @user_houses.present? %>
      <% @user_houses.each do |house| %>
        <div class="col-md-3 mb-4">
          <div class="card h-100" style="width: 19rem;">
            <% if house.photos.attached? %>
              <%= image_tag(cl_image_path house.photos.first.key, width: 400, height: 300, crop: :fill) %>
            <% end %>
            <div class="card-body d-flex flex-column">
              <h5 class="card-title"><%= house.address %></h5>
              <p class="card-text">Minimum Ask Price: <%= number_to_currency(house.price, precision: 0)%></p>
              <p class="card-text">No. of Offers: <%= Offer.where(house_id: house.id, status: 'Pending').length %></p>
              <% if Offer.where(house_id: house.id, status: 'Pending').present? %>
                <p class="card-text">Highest Offer: <%= number_to_currency(Offer.where(house_id: house.id, status: 'Pending').maximum(:price), precision: 0)%> </p>
              <% end %>
              <div class="mt-auto">
                <%= link_to "Check this out!", house_path(house), class: "btn btn-primary" %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    <% else %>
      <div class="col-md-12 text-center">
        <div>
          <%= image_tag 'empty.webp', alt: "No Houses" %>
          <h3>There are no listings yet.</h3>
        </div>
        <div>
          <%= link_to "Create a new listing", new_house_path, class: "btn btn-primary" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/houses/my_offers.html.erb
<div class="container mt-5">
  <div>
    <%= link_to :back, class: "btn" do %>
      <i class="fas fa-arrow-left"></i>
    <% end %>
  </div>
  <div class="text-center">
    <h1>My Offers</h1>
  </div>

  <div class="row justify-content-center mt-5">
    <% if @user_offers.present? %>
      <% @user_offers.group_by(&:house).each do |house, offers| %>
        <div class="col-md-4 mb-4"> <!-- Each card takes 4 columns on medium-sized screens -->
          <div class="card" style="width: 21rem;">
            <% if house.photos.attached? %>
              <%= image_tag(cl_image_path house.photos.first.key, width: 400, height: 300, crop: :fill) %>
            <% end %>
            <div class="card-body">
              <h5 class="card-title"><%= house.address %></h5>
              <p class="card-text">Minimum Ask Price: <%= number_to_currency(house.price, precision: 0) %></p>
              <p class="card-text">Your Offered Price: <%= number_to_currency(offers.last.price, precision: 0) if offers.last.present? %></p>
              <p class="card-text">Highest Offered Price: <%= number_to_currency(house.offers.maximum(:price), precision: 0) %></p>
              <p class="card-text">Date Created: <%= offers.last.created_at.strftime('%Y-%m-%d') if offers.last.present? %></p>
              <%= link_to "Check this out!", house_path(house), class: "btn btn-primary" %>
            </div>
          </div>
        </div>
      <% end %>
    <% else %>
      <div class="col-md-12 text-center">
        <div>
          <%= image_tag 'empty.webp', alt: "No Houses" %>
          <h3>There are no Offers yet.</h3>
        </div>
        <div>
          <%= link_to "View All Houses", houses_path, class: "btn btn-primary" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/houses/new.html.erb
<div class="container p-3">
  <h2>Create new house listing</h2>
  <%= render 'form' %>


    <%= link_to '< All houses', houses_path %>
</div>

app/views/houses/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-7">
      <h1><%= @house.address %></h1>
      <p>Listed By: <%= @house.user[:first_name] %></p>

      <% if current_user == @house.user %>
        <p class="text-success">You are the lister of this house</p>
      <% end %>

      <div>
        <%= link_to '< All houses', houses_path, class: "btn btn-secondary m-3" %>
        <%= link_to 'Edit', edit_house_path(@house), class: "btn btn-info m-3" if policy(@house).edit? %>
        <%= link_to 'Delete', house_path(@house), class: "btn btn-danger m-3", data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} if policy(@house).destroy? %>
      </div>

      <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-inner">
          <% @house.photos.each_with_index do |photo, index| %>
            <div class="carousel-item <%= 'active' if index == 0 %>">
              <%= cl_image_tag photo.key, class: "d-block w-100 img-fluid rounded carousel-inner-img"%>
            </div>
          <% end %>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>
      </div>

        <div class="house-info">
          <div class="house-info-section flex-row m-3 p-1">
            <p class="price"><%= number_to_currency(@house.price) %></p>
            <p class="price-per-sqft"><%= number_to_currency((@house.price.to_f / @house.square_feet).round(2)) %> psf</p>
          </div>
          <div class="house-info-section flex-row m-3 p-1">
            <p><%= @house.bedroom %> Bedrooms  <i class="fa-solid fa-bed"></i></p>
            <p><%= @house.bathroom %> Bathrooms <i class="fa-solid fa-toilet"></i></p>
            <p><%= @house.square_feet %> sqft <i class="fa-solid fa-ruler-combined"></i></p>
          </div>
        </div>

        <div class="house-details">
          <ul>
            <li>Region: <%= @house.region %></li>
            <li>Description: <%= @house.description %></li>
            <li>Type: <%= @house.property_type %></li>
            <li>Tenure: <%= @house.tenure %></li>
          </ul>
        </div>

      <%# Geocoding %>
      <div data-controller="map"
        id='map'
        data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"
        data-map-markers-value="<%= @markers.to_json %>"
        style="width: 100%; height: 600px;"
        class = "mt-3 mb-2"></div>

    </div>

    <div class="col-md-5" data-controller='favouritesbtn'>
      <div class="text-end" data-favouritesbtn-target="flashMessageContainer"></div>
      <div class="d-flex justify-content-end mb-3" >
        <% if current_user != @house.user%>
          <% if user_signed_in? %>
            <% if current_user.favourites.exists? %>
              <%= button_to '➖ Remove from Favourites', toggle_favourites_house_path(@house), method: :post, remote: true, class: "btn btn-primary is-favourites", data: { action: 'click->favouritesbtn#toggle', favouritesbtn_target: 'favourites'} %>
            <% else %>
              <%= button_to '➕ Add to Favourites', toggle_favourites_house_path(@house), method: :post, remote: true, class: "btn btn-primary", data: { action: 'click->favouritesbtn#toggle', favouritesbtn_target: 'favourites'} %>
            <% end %>
          <% else %>
            <%= button_to '➕ Add to Favourites', toggle_favourites_house_path(@house), method: :post, remote: true, class: "btn btn-primary", data: { action: 'click->favouritesbtn#toggle', favouritesbtn_target: 'favourites'} %>
          <% end %>
        <% end %>
      </div>

  <hr>

      <div>
        <h2>Current Offers</h2>
        <%= turbo_frame_tag "current_offers" do %>
        <table class="table table-striped table-hover" >
          <thead>
            <tr>
              <th>#</th>
              <th>Price</th>
              <th>Bidder</th>
              <th>Status</th>
              <th>Date Created</th>
            </tr>
          </thead>
          <tbody>
            <% @house.offers.order(price: :desc).each_with_index do |offer, index| %>
              <tr>
                <td><%= index + 1 %></td>
                <td><%= number_to_currency(offer.price, precision: 0) %></td>
                <td><%= offer.user.first_name  %></td>
                <td><%= offer.status  %></td>
                <td><%= offer.created_at.strftime('%Y-%m-%d') %></td>
                <% if offer.user == current_user && offer.status == 'Pending'  %>
                  <td>
                    <div class="d-flex flex-column">
                    <button type="button" class="btn btn-secondary btn-sm w-100 mb-1" data-bs-toggle="modal" data-bs-target="#offer-<%= offer.id%>">
                      Edit
                    </button>
                     <%= link_to 'Delete', offer_path(offer), class: "btn btn-warning btn-sm", data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
                    </div>
                  </td>
                <% else %>
                  <td></td>
                <% end %>
                <% if House.find(offer.house_id).user == current_user && offer.status == 'Pending'  %>
                    <td>
                      <div>
                        <%= button_to 'Accept', accept_house_offer_path(offer.house, offer), method: :post, class: 'update-offer-button btn btn-success btn-sm w-100 mb-1' %>
                        <%= button_to 'Decline', decline_house_offer_path(offer.house, offer), method: :post, class: 'decline-offer-button btn btn-danger btn-sm w-100' %>
                    </div>
                   </td>
                <% else %>
                  <td></td>
                <% end %>
              </tr>
            <% end %>
          </tbody>
        </table>
        <% end %>
        <% house_has_offer_by_current_user = @house.offers.any? { |offer| offer.user == current_user } %>
        <%#= current_user.id %>
        <%#= @house.offers.map {|offer| offer.user.id}.join(',') %>
        <% if current_user != @house.user && !house_has_offer_by_current_user && @house.offers.where(status: 'accepted').length < 1  %>
          <h2>Submit an Offer</h2>
          <%= simple_form_for [@house, @offer] do |f| %>
            <%= f.input :price, error: @offer.errors[:price], class: "form-control" %>
            <%= f.submit "Submit Offer", class: "btn btn-primary" %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>

</div>

<% @house.offers.each_with_index do |offer, index| %>
                  <div class="modal fade" id="offer-<%= offer.id%>" tabindex="-1" aria-hidden="true">
                    <div class="modal-dialog">
                      <div class="modal-content">
                        <div class="modal-header">
                          <h1 class="modal-title fs-5">Edit Offer</h1>
                          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <%= simple_form_for [@house, offer] do |f| %>
                          <div class="modal-body">
                            <%= f.input :price, error: offer.errors[:price], class: "form-control" %>
                          </div>
                          <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                            <%= f.submit "Submit Offer", class: "btn btn-primary" %>
                          </div>
                        <% end %>
                      </div>
                    </div>
                  </div>
<% end %>